; Medical Spytool Inno Setup Script for PyInstaller Bundled Application

#define MyAppName "MedicalSpytool"
#define MyAppVersion "2.0" ; Update this with your application's version
#define MyAppPublisher "Your Publisher Name"
#define MyAppURL "https://www.example.com/"
#define MyAppExeName "MedicalSpytool.exe" ; This will be the .exe generated by PyInstaller
#define MyAppIconName "MedicalSpytool.exe" ; Assuming icon is embedded in exe, or add icon.ico to dist and use "icon.ico"

[Setup]
AppId={{YOUR_UNIQUE_APP_ID_GUID}} ; Generate a new GUID for your app
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes ; Simplifies installation if no group page needed
PrivilegesRequired=admin ; If your app needs admin rights to install or run certain parts
OutputBaseFilename=MedicalSpytool-Setup-{#MyAppVersion}
Compression=lzma
SolidCompression=yes
WizardStyle=modern
SignTool=signtool_command_here_if_you_have_a_certificate ; Optional: for code signing

[Languages]
Name: "german"; MessagesFile: "compiler:Languages\German.isl"
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}";
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; OnlyBelowVersion: 0,6.1; Flags: unchecked;

[Files]
; Source: "Path\To\Your\PyInstaller\Output\MedicalSpytool\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; The path below assumes build.py places the output in dist\MedicalSpytool relative to this .iss file
Source: "dist\{#MyAppName}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; Example for including a specific icon if not embedded (place icon.ico in dist\MedicalSpytool):
; Source: "dist\{#MyAppName}\icon.ico"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\{#MyAppIconName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon; IconFilename: "{app}\{#MyAppIconName}"
Name: "{autoquicklaunch}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: quicklaunchicon; IconFilename: "{app}\{#MyAppIconName}"

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[UninstallDelete]
Type: files; Name: "{app}\*" ; Remove all files in the app directory

[Code]
// Optional: Check for .NET Framework or other prerequisites if your app needs them.
// The Python check from the original script is less relevant if PyInstaller bundles Python,
// but could be adapted if a system-wide Python is still interacted with by the bundled app.

// function IsPythonInstalled: Boolean;
// var
//   PythonInstalled: Boolean;
//   ResultCode: Integer;
// begin
//   // This check might be too simple or not needed for a bundled app
//   if Exec(ExpandConstant('{cmd}'), '/C python --version', '', SW_HIDE, ewWaitUntilTerminated, ResultCode) then
//   begin
//     Result := (ResultCode = 0);
//   end
//   else
//   begin
//     Result := False;
//   end;
// end;

// function InitializeSetup: Boolean;
// begin
//   // if not IsPythonInstalled then
//   // begin
//   //   MsgBox('Python 3.x is recommended to be available on the system, though this application is bundled.' + #13#10 +
//   //          'If you encounter issues, please ensure Python is installed and in PATH.', mbInformation, MB_OK);
//   // end;
//   Result := True;
// end;

// Procedure to be called when the setup finishes.
// Could be used to clean up temporary files or perform other post-install tasks.
// procedure CurStepChanged(CurStep: TSetupStep);
// begin
//   if CurStep = ssDone then
//   begin
//     // Example: MsgBox('Installation complete!', mbInformation, MB_OK);
//   end;
// end;
